# Site settings
title: William Pittman
email: liam@wspittman.com
description: >-
  Data journalist mapping the systems that shape civic life and making hidden infrastructure visible, accountable.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liampittman.github.io/" # the base hostname & protocol for your site
github_username: liampittman

# Build settings
markdown: kramdown
permalink: /:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md
